-- Temporarily disable RLS for profile stats testing
ALTER TABLE achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE gym_friends DISABLE ROW LEVEL SECURITY; 
ALTER TABLE gym_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE workout_sessions DISABLE ROW LEVEL SECURITY;;
