name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install root deps
        run: npm ci || npm install

      - name: Install app deps
        run: npm --prefix gymtopia-app ci || npm --prefix gymtopia-app install

      - name: Run E2E tests
        env:
          CI: 'true'
        run: npm --prefix gymtopia-app run e2e:test
